from collections import namedtuple

TAMANNO_LETRA = 20
FPS_inicial = 30
TIEMPO_MAX = 60

ANCHO = 800
ALTO = 600
COLOR_LETRAS = (20,200,20)
COLOR_FONDO = (0,0,0)
COLOR_TEXTO = (200,200,200)
COLOR_TIEMPO_FINAL = (200,20,10)
Punto = namedtuple("Punto","x y")

VOCALES = "aeiou"
DIFICILES = "jkqwxyz"

PANTALLA_JUEGO = "PANTALLA_JUEGO"
PANTALLA_INICIO = "PANTALLA_INICIO"
PANTALLA_PUNTAJES = "PANTALLA_PUNTAJES"

TECLA_ARRIBA = 273
TECLA_ABAJO = 274
TECLA_ENTER = 13
